### ISSUE TITLE
Attempting to open settings before gaining storage priviledge crashes app.

### ISSUE THREAD

**Issue by tmsrise** [MenosGrante/Rekado#10]
I kept trying to access settings in the fresh install from the instructions tab, but it kept crashing the app. It only started working after I went into the payloads tab and it requested for storage permissions. I'm guessing accessing settings required that permission and the app panic-crashed when it didn't have said permissions. 

Galaxy S8+  Oreo.

**Comment by MenosGrante** [comment]
Yes, I can reproduce it. Will be fixed in 2.2 update.

**Comment by MenosGrante** [comment]
Fixed in 2.2 update!

**Comment by adrenochrome25** [comment]
i had exactly the same behavior with 2.3, in fact the storage permission was even already granted, but prefs kept on crashing until i went to payload tab and added some
