### ISSUE TITLE
Availability on F-Droid

### ISSUE THREAD

**Issue by LividJava** [MenosGrante/Rekado#103]
Is there any chance of this app being published on the F-Droid repository? I ask because it would make pushing updates much easier on the end users.

**Comment by MenosGrante** [comment]
I have tried to publish it in the past and at that time I could not do it, because some parts of the app are hidden behind my own libraries, which I don't won't to publish.

**Comment by Juicyvag** [comment]
that's why I can't use this app.   It never worked for me at all.  it crashes and tried to debug it and it came to your closed source libs.

**Comment by MenosGrante** [comment]
I have plans to get rid of some functions in the 4.2 update (that includes my closed source libs).
