### ISSUE TITLE
lakka bootloader has been updated

### ISSUE THREAD

**Issue by plaidman** [MenosGrante/Rekado#11]
If you download the nightly build, you can find the new version of the bootloader in /lakka/boot/

https://transfer.sh/12wmvL/Lakka_nightly.tar

**Comment by MenosGrante** [comment]
Updated in Rekado 2.1.1. In future 2.2 release in will probably not shiped with application and users will need to add/update it manually.

**Comment by plaidman** [comment]
cool. In the near future, Hekate will be updated to be able to load Lakka anyway, so that feature might not be needed. It has been nice to have both in the same app in the mean time though. =)
