### ISSUE TITLE
Feature request: android 13 themed icon

### ISSUE THREAD

**Issue by Filyx20** [MenosGrante/Rekado#112]
Hi there, i am currently wondering if adding support to having themed icons for Android 13 could be added?
Added [Here](https://developer.android.com/about/versions/13/features#themed-app-icons) is the URL towards the android developer site about the new feature.

Have a wonderful day and thanks you.

**Comment by MenosGrante** [comment]
Support for Android 13 and themed icon added as part of 5.1 update.
