### ISSUE TITLE
Hard to read "Serial Checker" button on dark mode

### ISSUE THREAD

**Issue by TxMat** [MenosGrante/Rekado#114]
Hello,
This is a very minor issue but the button "serial checker" is very hard to read and most likely does not respect the minimum contrast recommended for accessibility

![Screenshot_2022-06-29-17-41-48-461_com.pavelrekun.rekado.png](https://user-images.githubusercontent.com/46858765/176480143-6659cfec-7293-4391-8e85-e716de1e49f0.png)

What about using a darker blue ?

Have a nice day

**Comment by MenosGrante** [comment]
Thank you for reporting! Fixed in 5.1 update.
