### ISSUE TITLE
[Question] Did you update fusee.bin after the silent update?

### ISSUE THREAD

**Issue by OrGoN3** [MenosGrante/Rekado#117]
Atmosphere had a silent update shortly after transitioning from pre release to regular release. Fusee.bin was changed in this update to fix an booting issue with exfat and nogc.

I know you updated fusee.bin before the silent update. Was it updated again after?

Thanks!

**Comment by MenosGrante** [comment]
Hello, it wasn't updated after the final version was released, however, I have pushed the latest Fusee version. Thank you for letting me know!
