### ISSUE TITLE
Check for Updates error "connection closed"

### ISSUE THREAD

**Issue by mikitakahazekura** [MenosGrante/Rekado#118]
When I click on "Check for Updates" on the Payload Tab, I get "connection closed" error.
![photo_2023-03-10_19-46-12](https://user-images.githubusercontent.com/24222032/224400329-35b308ba-4976-42fe-9075-4c1665d0bf7a.jpg)

**Comment by MenosGrante** [comment]
Hello, this error occurred after my previous domain (pavelrekun.dev) died and was replaced with pavlorekun.dev. I am going to release a new minor update to resolve it. Thanks for reporting.

**Comment by MenosGrante** [comment]
New release available, thanks again - https://github.com/MenosGrante/Rekado/releases/tag/5.1.2.
