### ISSUE TITLE
[Enhancement] Add Payloads

### ISSUE THREAD

**Issue by mikitakahazekura** [MenosGrante/Rekado#119]
Add suchmememanyskill's [Tegraexplorer](https://github.com/suchmememanyskill/TegraExplorer) and shchmue's [Lockpick_RCM](https://github.com/shchmue/Lockpick_RCM) in the bundled payloads.

**Comment by MenosGrante** [comment]
I guess you are aware of what currently happening to Lockpick, so currently I don't have plans to update list of bundled payloads, sorry.
