### ISSUE TITLE
sending payload failed at offset 65536

### ISSUE THREAD

**Issue by Norpordorp** [MenosGrante/Rekado#12]
Rekado has seemingly stopped working now that I've switched to using SX OS. Everything worked fine before (on NXloader v0.2 & running ReiNX/Hekate), but after switching to SX OS and using Rekado instead of NXloader, it has simply stopped working. NXloader kicks me back to the main screen, and Rekado spits out "sending payload failed at offset 65536". It's not just SX OS, it rejects every payload now. I'm not entirely convinced that the problem is my OTG adapter, because it worked fine a few days ago and I can still use the OTG adapter with an external HDD and my phone and it pulls data just fine. Here is the adapter I use: https://www.amazon.com/UGREEN-Adapter-Samsung-Controller-Android/dp/B00N9S9Z0G/ref=sr_1_3?ie=UTF8&qid=1533790293&sr=8-3&keywords=usb+3+to+micro+usb What is going on?

**Comment by MenosGrante** [comment]
Sending payload is cable/adapter error. Have you changed it?

**Comment by Norpordorp** [comment]
I haven't changed the cable or the adapter. The cable is a Pro Controller original cable, and the OTG adapter is the one I links above. The cable still works fine when I use it on my PC, but doesn't work anymore on my phone. Do I need a new cable or a new adapter?

**Comment by Norpordorp** [comment]
The issue still hasn't gone away. I'm open to purchasing a new OTG adapter. Is there one in particular that you recommend for use with Rekado?

**Comment by MenosGrante** [comment]
For my OnePlus 5 I am using Ugreen OTG Type C adapter with original cable.

**Comment by MenosGrante** [comment]
Duplicate #9
