### ISSUE TITLE
Patched or not patched? That is the question. 

### ISSUE THREAD

**Issue by n3rdcub** [MenosGrante/Rekado#124]
Terrible Shakespeare jokes aside, according to this comment https://github.com/MenosGrante/Rekado/issues/93#issuecomment-821888764 if your app shows it attempted to push a payload that means my decice isn't patched? 

It's not very clear, either on GitHub or in comment; if a patched device tries to push payload what Actually happens? Does it try to push still? Is there any sort of success or failure message? Is there any indication your app successfully or failed to achieve what it's trying to do and conveys it to the user? How can I tell anything happened besides the logs showing it pushed a payload but device seems the same

**Comment by githubUser01946** [comment]
According to [this](https://switch.homebrew.guide/gettingstarted/checkingrcm) it would mean it's not worked.

`A success message should now be displayed on your Switch. If so, celebrate! Your Switch is vulnerable and you can now push payloads!`

`If` the application says the payload launch was successful, but nothing appears on your screen, unfortunately your Nintendo Switch is likely patched. You should try a few more times to be certain, and consider trying another USB cable. If your Switch is patched and running firmware 4.1.0, you can still access CFW. If your Switch is patched and running a higher firmware version, unfortunately your Switch cannot be hacked right now.`
