### ISSUE TITLE
Updater Not Working

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [MenosGrante/Rekado#128]
"That's why I have created a mechanism to deliver payload updated via an in-app update mechanism. When you come to the "Payloads" screen in the app, just swipe to refresh and the app will check if there are any updates to payloads available. I am storing the config for these updates on my personal site and keeping track of updates."

This is not working so your config needs to be updated. Hekate 6.1.0 released three days ago.

**Comment by MenosGrante** [comment]
Update was released recently, thanks for notificing.

**Comment by harvestry-of-ghosts** [comment]
> Update was released recently, thanks for noticing.

There is no updated apk here and the app says already using the latest payloads. Where is the update?

**Comment by MenosGrante** [comment]
Yes, the online config was a little bit messed and the updater didn't receive new updates because of it. The issue is resolved now and Hekate 6.1.0 is available for update from the app. Thanks for letting me know about the issue.
