### ISSUE TITLE
App Does Not Download Latest Hekate 6.1.0

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [MenosGrante/Rekado#129]
Open Rekado > Select Payloads Section > Click on "Check for Updates"  
The app just says "No Updates. No updates were found. You are using the latest built-in payloads".

The app stays on Hekate 6.0.7 even though 6.1.0 is hosted at https://pavlorekun.dev/payloads/hekate.bin. As previously stated, the in app updater is not working correctly. You closed the prior issue #128 without fixing it. You have the correct latest file hosted, but the app is not downloading it when using the update feature.

**Comment by MenosGrante** [comment]
Yes, the online config was a little bit messed and the updater didn't receive new updates because of it. The issue is resolved now and Hekate 6.1.0 is available for update from the app. Thanks for letting me know about the issue.
