### ISSUE TITLE
Hekate Needs To Be Updated

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [MenosGrante/Rekado#133]
Hello. I see Rekado did auto update to Hekate 6.2.0. However, there was a mistake in the initial release of it that caused a crash. 6.2.0 was fixed and reuploaded, but Rekado does not update to the fix because it thinks it is already on the latest with the same number. I tried uninstalling Rekado, reinstalling, and then running the auto-updater again but it still downloads the broken version of 6.2.0. Rekado must be updating from a cache that needs to be refreshed from your end of things, instead of grabbing the fixed release.

**Comment by MenosGrante** [comment]
Hi, thanks for reporting this, I have updated Hekate to V3.

**Comment by harvestry-of-ghosts** [comment]
> Hi, thanks for reporting this, I have updated Hekate to V3.

Thank you! However, it was updated again today to v4. Please update again. :)
