### ISSUE TITLE
Hekate and Fusee Built In Payloads Need Updating

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [MenosGrante/Rekado#134]
Hekate was updated again today to 6.2.0 v4 but version number still didn't change so Rekado auto-update won't pull the latest. Fusee also received a silent update after it's initial release of 1.7.1. Version also didn't change so Rekado can't auto-update. Please update both on your end. Thanks again!

**Comment by MenosGrante** [comment]
Updated both, thanks for letting me know.

**Comment by Nameless1981** [comment]
Still have blue screen with the embedded Hekate.bin, no problem if I put manualy the last version.
