### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by robinknaapen** [MenosGrante/Rekado#16]
When looking through the app I've found a small UI bug,

When switching tabs with the bottom navbar I ended up in the payload section. After that I've opened settings and changed the accent color. When leaving the settings I will be back at the Instructions tab while the Payloads tab is still highlighted.

Steps to reproduce

1. Open __any other__ tab than Instructions
2. Open settings
3. Change accent color to a color that is __not__ currently active
4. Go back by using the back button
5. You will be in the Instructions tab while the other tab is highlighted

**Comment by MenosGrante** [comment]
Thank you, will fix this bug in 2.4 update.

**Comment by MenosGrante** [comment]
2.4 update with fix for this bug released.
