### ISSUE TITLE
Give option to remove bundled payloads completely.

### ISSUE THREAD

**Issue by Clydefrosch22** [MenosGrante/Rekado#18]
Both the Reinx and sx payloads will regenerate, if removed from the Rekado folder and while I think its good to bundle those with the app in general, I think it should be possible to remove them if you don't want them.
At the very least, add some option to not have unwanted payloads display when connecting to a switch in RCM mode.
Thank you

**Comment by MenosGrante** [comment]
This improvement will be added in 2.4 update.
