### ISSUE TITLE
I like Rekado, So I translated him into Chinese.

### ISSUE THREAD

**Issue by carlchina** [MenosGrante/Rekado#19]
I like Rekado, So I translated him into Chinese.

[values-zh_cn.zip](https://github.com/MenosGrante/Rekado/files/2370465/values-zh_cn.zip)

**Comment by MenosGrante** [comment]
Well, I will add it, but in future it will be better to update it using Pull requests.

**Comment by MenosGrante** [comment]
@carlchina Look at localization section in [README](https://github.com/MenosGrante/Rekado#faq) and update your localization, please.
