### ISSUE TITLE
no response 

### ISSUE THREAD

**Issue by XanderOX92** [MenosGrante/Rekado#21]
When im trying to connect my switch to my Essential phone PH1 (running on android pie)
there is no response from android side.
no payload request message. 
i used several type c-type c cords on my other devices (android 8) and all of them work.
seems like there is an issue with essential phone/android 9.

**Comment by CapnSammeh** [comment]
I am actually having the same issue using Android Pie Beta on my OnePlus 6. 

Log output is only showing that the application is starting, not that it detects a device has been connected. 

Ive tried using a USB C to C cable, and an OTG C + A -> C Cable without success.

**Comment by MenosGrante** [comment]
@CapnSammeh Have you enabled OTG in Advanced settings? Some OnePlus devices requires this setting to be enabled.

**Comment by CapnSammeh** [comment]
@MenosGrante, that's done it! After enabling the OTG Setting, Rekado is working as expected.

Thanks for the help, and the amazing app!

**Comment by XanderOX92** [comment]
Nothig happens,i dont seem to have any otg settings. Only usb settings. I gave storage permission and the log shows nothing but "Application started"

**Comment by MenosGrante** [comment]
@XanderOX92 Do you have OnePlus device? If yes, you should have "Advanced" category in Settings and this setting will be there. Also, if you have root, you can install Magisk module - "OTG Enabler" and you will not need to enable it every time.

**Comment by XanderOX92** [comment]
![image](https://user-images.githubusercontent.com/30697489/47604037-df87b900-d9fc-11e8-8991-e13801fea954.png)
![image](https://user-images.githubusercontent.com/30697489/47604039-e7dff400-d9fc-11e8-84ea-e43bc036c819.png)
![image](https://user-images.githubusercontent.com/30697489/47604042-ee6e6b80-d9fc-11e8-9cdf-d9ba00ed7935.png)
 btw,my otg adapter works with thumb drives and mouse/keyboards. so i believe enabeling OTG is not the issue here

**Comment by mars0124** [comment]
I'm not sure if I'm supposed to submit a new issue or piggyback on this one, so if I'm taking the wrong approach please advise!

I'm using a Samsung S6 Egde+ that is having the above issue.  There's nothing in the log to indicate an OTG connection.  I'm using a modified version of the original firmware where Samsung bloat has been stripped ad Magisk included.  Not sure what else to include, so if there's something let me know!

Thanks!

**Comment by GerkinDev** [comment]
Hi people!
I have a xperia xz1 with android 9, and I am in the same case than @XanderOX92, with the exact same screens. After some researches, it seems that even if my device supports USB host, it does not support OTG (yeah Sony sometimes miss important features). I did not find a way to make it work. I guess I'll try from another phone.

Great job anyway :) but it would be convinient to have some informations about known issues or unsupported devices from the app ;)
