### ISSUE TITLE
is there any plan to place it on play store?

### ISSUE THREAD

**Issue by wendyliga** [MenosGrante/Rekado#26]
is there any plan to place it on play store? I would really happy to help you upload your app to Play Store if you want

or there is some restriction on Play Store ?

**Comment by MenosGrante** [comment]
Actually, there is no plans to place it in Google Play, because I don't want to draw attention to my account. Actually, I think about replacing AppUpdater (that is not working currently) and load application in F-Droid (this is alternative of Google Play for open-source apps).
