### ISSUE TITLE
Das Sende des Payload, von meinem Note 9 geht nicht.

### ISSUE THREAD

**Issue by Conan179** [MenosGrante/Rekado#36]
Hallo erst mal.
Ich wollte, mit meinem Note 9 das Payload an meine Switch schicken.
Ich nutzte dafür das USB-C lade kabel (usb 2.0) von meinem Netzteil und den OTG Adapter wo beim Note9 beilag.
![2019-01-23 21 38 25](https://user-images.githubusercontent.com/1906242/51636038-83c7c000-1f58-11e9-97f3-0c65ba394acb.jpg)

**Comment by MenosGrante** [comment]
I don't understand Deutsch, could you please translate it to English?

**Comment by MenosGrante** [comment]
No answer for 18 days. I am closing this issue.
