### ISSUE TITLE
Rekado doesn't launch 

### ISSUE THREAD

**Issue by BlitzBot-v01** [MenosGrante/Rekado#39]
The app just crashes as soon as i open it. Im on my Samsung note 9 running Android 8.1.

**Comment by MenosGrante** [comment]
Hello, do you have Root on your phone, if yes, could you please get logcat from it?

**Comment by kuroyukihime0** [comment]
I post my crash log on https://github.com/MenosGrante/Rekado/issues/33

**Comment by RussKay** [comment]
Crashes for me upon launch. Reverted back to 2.6. Pixel 3, Android 9 with February 5 security patches/update. Never rooted or modified my phone in any way.

**Comment by MenosGrante** [comment]
Thank you for feedback. Let's move discussion in #33.
