### ISSUE TITLE
F-Droid or Google Play Store Release?

### ISSUE THREAD

**Issue by CarJem** [MenosGrante/Rekado#4]
Would be nice to automatically grab the latest stable releases.

**Comment by MenosGrante** [comment]
Release on the Google Play Store is unlikely. Google is likely to just ban application and account. I am still thinking of a release in the F-Droid or a mechanism for updating from the application itself.

**Comment by MenosGrante** [comment]
I have added self updater inside application. It will be available in next update (probably tomorrow).

**Comment by MenosGrante** [comment]
Self updater added in update 1.3.
