### ISSUE TITLE
App crashes when sending payload with auto injector enabled

### ISSUE THREAD

**Issue by Akorax** [MenosGrante/Rekado#44]
Enabling "Auto Injector" crashes the app upon sending of payload.
Everything works fine with "Auto Injector" disabled

Environment: Livingroom
Phone: Samsung Galaxy S7
Cable: MicroUSB to USB-A adapter + USB-A to USB-C cable.
Rekado: 3.0 (50)
Payload: Hekate CTCaer 4.10.1

**Comment by MenosGrante** [comment]
Thank you for detailed report, I will check this issue and will get back to you.

**Comment by MenosGrante** [comment]
I have successfully reproduces this issue on my device and I am going to fix it in 3.1 update.

**Comment by MenosGrante** [comment]
Hi @Akorax, I have just release 3.1 update and it should fix this defect. Could you confirm it?

**Comment by Akorax** [comment]
@MenosGrante A-mazing! It works like a charm and I don't even have to unlock my phone to use it! <3<3<3

**Comment by MenosGrante** [comment]
Thank you for verification. Closing this defect.
