### ISSUE TITLE
Suggestion: Make serial checker work with lowercase letters

### ISSUE THREAD

**Issue by Akorax** [MenosGrante/Rekado#45]
As stated in the title. It would be an improvement if you didn't need to use uppercase when typing in the serial numbers in the serial checker function. :)

Edit: Right now you get "can't check this serial number" when using lowercase letters.

Phone: Samsung Galaxy S7
Rekado version: 3.0

**Comment by MenosGrante** [comment]
Implemented and will be available in 3.1 update.
