### ISSUE TITLE
Suggestion: Serial checker information text

### ISSUE THREAD

**Issue by Akorax** [MenosGrante/Rekado#46]
I suggest changing the information text slightly. Giving each header a bold text and removing some unnessescary text.

From:

Serials beginning with XAW:
XAW10000000000-XAW10074000000: Not patched
XAW10075000000-XAW10120000000: Possibly patched
XAW10120000000 and higher: Patched
... and so on ...

To:

**XAW**
XAW10000000000-XAW10074000000: Not patched
XAW10075000000-XAW10120000000: Possibly patched
XAW10120000000 and higher: Patched
... and so on ...

Phone: Samsung Galaxy S7
Rekado version: 3.0

This is just a minor graphical enhancement but I feel like it could be worthwile to implement.

Edit: I might read a bit quick sometimes but I actually read it like XAW10074000000 would be safe all the way up to XAW10074999999 since the next range begin at XAW10075000000 which isn't confirmed yet afaik.

**Comment by MenosGrante** [comment]
I think that it is not very important change, which does not introduce anything but not significantly reducing the text. I do not plan to make these changes yet.
