### ISSUE TITLE
Suggestion: Serial checker Lettercounter and Length restriction

### ISSUE THREAD

**Issue by Akorax** [MenosGrante/Rekado#47]
A letter counter for the serial checker input box would be great! It could be on the side or below the box. Also, limiting the input to be no more than 14 symbols would limit people from typing incorrect serials.

Example:

XAW10000000001 14/14
XAW1000000000   13/14
XAW100000000     12/14

Phone: Samsung Galaxy S7
Rekado version: 3.0

**Comment by MenosGrante** [comment]
Implemented and will be available in 3.1 update.
