### ISSUE TITLE
Not letting me send payload from Razer phone

### ISSUE THREAD

**Issue by cpenny1** [MenosGrante/Rekado#48]
I have downloaded the payload but when I connect my switch to the phone nothing happens. I know it's connected as I can select whether to transfer files or charge the switch from my phone. Im using a usb type c to usb type c

**Comment by MenosGrante** [comment]
It can be connected, but to send files your phone should support OTG. Try to Google if you device supports it and try to enable it.

**Comment by cpenny1** [comment]
I gave up with my razer phone but my old samsung galaxy s7 edge with the otg adapter that came with it works. 

Maybe a suggestion is to make a post on reddit/gbatemp or whatever and make a list of all confirmed working phones. :)

**Comment by MenosGrante** [comment]
It may be not problem with phone, but with USB cable sometimes, but in your case it seems, that this is problem with OTG support.

So, if it works on another device now I will close this issue.
