### ISSUE TITLE
Stuck at Nintendo Switch logo

### ISSUE THREAD

**Issue by pb1051** [MenosGrante/Rekado#49]
I'm going to try this version later today, but I was getting stuck on the Nintendo Switch logo with the previous version after updating Kosmos through the tool. Will report back after trying this evening.

**Comment by MenosGrante** [comment]
Hello @pb1051, can you tell me which payload are you using?

**Comment by pb1051** [comment]
I was using the hekate in rekado 3.0 (50)
_________________________________
Paul N. Bailey
Contact: (281)770-4796 <#SignatureSanitizer_SafeHtmlFilter_>

**Comment by MenosGrante** [comment]
Have you tried to use Rekado 3.1 with built in Hekate 5.0.0?

**Comment by pb1051** [comment]
@menosgrante I have tried this version and payload. Still stuck on the Switch logo. Should I try a different payload?

**Comment by MenosGrante** [comment]
You can try, but I guess it will be the same result.

**Comment by Akorax** [comment]
If you get all the way to the Switch Logo the payload should already be injected. It's probably not the app at this stage.

**Comment by pb1051** [comment]
Cleared out my SD card and reloaded it. All good!
