### ISSUE TITLE
Automatically Download/Update common Payloads

### ISSUE THREAD

**Issue by Luro02** [MenosGrante/Rekado#51]
I know, that there are a few payloads bundled with Rekado and that you can add new ones from the storage or an url, but this is a very tedious process and I don't want to always go to github and download the latest releases of every payload on my smartphone.
Therefore I propose to include a feature, that automatically downloads payloads from for example github (via the api?), so you don't have to update them manually.

Also may you add/bundle fusee-primary (the payload from Atmosphere release). It's way faster, than navigating through the hekate menu.

**Comment by Akorax** [comment]
I don't think it's much of a hassle getting the payloads on the phone manually and finding them with the app after that. (the storage access framework is really easy to use). However, I like this suggestion as it would automate things more and that's the best thing about Rekado imo.

**Comment by MenosGrante** [comment]
I guess bundling fusee-primary.bin is pretty good idea. Speaking about using GitHub API to download payloads is overcomplicating application's logic, so I would not wait for this feature in near future.
