### ISSUE TITLE
Suggestion: Barcode scanner

### ISSUE THREAD

**Issue by Akorax** [MenosGrante/Rekado#52]
A barcode scanner to use with the serial checker would be awesome. That way you only need to type the serial if the barcode doesn't read in the first place. Maybe a flashlight toggle could be implemented here as well if the environment is dim when scanning.

The function could just send the results to the already existing text field in the serial checker activity. (also don't forget to prevent crashes if someone scans a too long serial)

P.S I also found a [link](https://ariefbayu.xyz/create-barcode-scanner-for-android-using-kotlin-b1a9b1c4d848) where they show an example of how to do a barcode scanner in kotlin.
P.S 2 I know there are apps and sites that have this function today but they're neither open source nor capable of sending payloads afaik.

**Comment by MenosGrante** [comment]
I will dive into this and check if it is possible to create such functionallity.

**Comment by MenosGrante** [comment]
Implemented in 94540135d982de6f09c81110bea9a50ea8505e5d commit and should be available in 3.2 update.
