### ISSUE TITLE
Device can't detect Nintendo Switch in RCM mode

### ISSUE THREAD

**Issue by enfedal** [MenosGrante/Rekado#53]
the app doesn't detect that my switch is in rcm mode.

**Comment by MenosGrante** [comment]
Hey @enfedal, have you checked if your device compatible with Rekado's requirements? It should support OTG (and have it enabled) and use specific cable for data transfering. Check if your OTG connection enabled first.

**Comment by theicecube** [comment]
i have this problem as well, and i verified all the requirements are met
phone is galaxy j7 2016, supports usb otg
i know the cables i'm using work because it picks up my switch and my phone on my pc, and my phone's cable lets me transfer data between my pc and phone, and yet the app doesn't detect my switch

**Comment by enfedal** [comment]
i tried it with a samsung galaxy s5 and s8+ my cable is capable of data transfering. it didn't work with either one of them and the s8 definitely supports otg so i was hoping you would know why its not working

**Comment by MenosGrante** [comment]
Most of Samsung device does not working with Rekado currently and I haven't found the reason now. Currently you can try another applications like RCM Loader, NXLoader or anything like this.

**Comment by knerlington** [comment]
Have been having the same issue forever using both android 9 (stock rom) and now lineageos with android 10 as a base. What I did just now was to clear the app storage for Rekado. Plugged the USB C cable into my switch and then my phone (xz1 compact which is entirely OTG compatible) and waited about 3 seconds without doing anything and then a prompt showed up asking if I wanted to handle APX or "the APX connection" or something like that with Rekado. Pressing ok allows me to finally push payloads to my Switch. I had auto injection enabled btw. So a driver of sorts used to recognize and handle APX mode on Tegra devices is/was missing on my device?
