### ISSUE TITLE
everything is perfect but it doesnt work

### ISSUE THREAD

**Issue by silveromg** [MenosGrante/Rekado#57]
when i connect Autorcm switch to my phone
my phone runs rekado and i choose a payload which i use
then my switch is off
nothing happened
i have changed my cable and otg twice
but that was not good point
my allowance 15000 won was disappeard 
plz i want to run my switch with Android

**Comment by silveromg** [comment]
my phone is s9

**Comment by MenosGrante** [comment]
Hello, could you check, if there is any information in "Logs" category?

**Comment by silveromg** [comment]
https://imgur.com/a/i2br8r6

**Comment by silveromg** [comment]
i checked closed issues
is error code 65536 sign my cable is wrong?
omg i definitely changed cable and otg twice

**Comment by silveromg** [comment]
i'll try to change otg one more time
thank you for your reply

**Comment by MenosGrante** [comment]
Yeah, in most cases this error means problems with used Cable\OTG adapter, try to use another one.
