### ISSUE TITLE
OnePlus 6 and Switch 

### ISSUE THREAD

**Issue by TheMongoStomp** [MenosGrante/Rekado#58]
Getting this error code. Not sure if it's my device or my cables. 
![Screenshot_20190829-212745](https://user-images.githubusercontent.com/54708519/64015268-28633f00-caf2-11e9-8f03-9a1630e9221c.jpg)

**Comment by MenosGrante** [comment]
Hey, all "Sending payload failed at offset" errors occurs due to bad cables\adapters, so just try another one. I had OnePlus 5 and it was working properly with original cable + UGreen OTG adapter.

**Comment by MenosGrante** [comment]
Closing this issue because of the lack of response.
