### ISSUE TITLE
Galaxy S8+ doesn't seem to detect Nintendo Switch

### ISSUE THREAD

**Issue by GuyInDogSuit** [MenosGrante/Rekado#59]
The Switch is in RCM mode, and I have SX OS, but I haven't been able to load it or anything else with this device. Not sure what I'm doing wrong.

**Comment by MenosGrante** [comment]
Does your phone can detect Nintendo Switch in RCM mode?

**Comment by GuyInDogSuit** [comment]
No, doesn't seem to recognize it.

**Comment by MenosGrante** [comment]
I have answered a similar question in [another issue](https://github.com/MenosGrante/Rekado/issues/56).
