### ISSUE TITLE
Device question

### ISSUE THREAD

**Issue by Mika-Westphal** [MenosGrante/Rekado#61]
My Samsung Galaxy A5 2017 can't detect the switch and i know that you don't know why. But i simply ask if it is possible that this [patch](https://github.com/fail0verflow/shofel2/blob/master/linux-ehci-enable-large-ctl-xfers.patch) can fix it when it's used in the kernel? So what du you think about the

**Comment by MenosGrante** [comment]
I have answered a similar question in [another issue](https://github.com/MenosGrante/Rekado/issues/56).

The kernel doesn't affect anything in this case.
