### ISSUE TITLE
USB Type C to USB Type C also works

### ISSUE THREAD

**Issue by frosty5689** [MenosGrante/Rekado#63]
Hi,

I just wanted to let people know using a quality USB Type C to USB Type C cable also works. I tested this on my OnePlus 7 Pro. I don't need to enable OTG either as this is part of the new USB Type C spec that auto negotiate who is host. Just thought I'd let people know since its not mentioned in the README as an option

**Comment by MenosGrante** [comment]
Great, I am also used USB Type C to USB Type C from UGreen with my OnePlus 5 and using it now with Pixel 3. I will update the readme with this info. Thank you.
