### ISSUE TITLE
Wear OS Support

### ISSUE THREAD

**Issue by frosty5689** [MenosGrante/Rekado#64]
So it seems like Wear OS has basic OTG, but no drivers for mouse/keyboard and other peripherals. Wondering if it'll work for sending RCM payloads. It would be super cool if it does. I don't have a Wear OS watch to install the APK and test it though.

**Comment by MenosGrante** [comment]
I am also don't have any Wear OS devices and the platform seems really dead :( Maybe with the release of  Pixel Watch in far future it will become more lively, then we can get back to this theme.
