### ISSUE TITLE
Crash when trying to open the "Accent color" dialog

### ISSUE THREAD

**Issue by TheLastZombie** [MenosGrante/Rekado#65]
I'm on the latest version (3.2.3). To reproduce, open Rekado, go to Settings and tap on "Accent color".

![Screenshot_20191130-122135](https://user-images.githubusercontent.com/8181990/69899817-f7520f00-136b-11ea-9e46-6fc0fe9b5151.jpg)

Device: OnePlus 7 Pro (GM1913)
OS: Oxygen OS 10.0.1.GM21BA (Android 10)

**Comment by MenosGrante** [comment]
Hey, I can also reproduce it :( Will take a look at the root soon. Thank you for reporting it.

**Comment by MenosGrante** [comment]
Fixed in 3.2.4 update. Thank you for reporting, again.
