### ISSUE TITLE
[Payload] Add fusee-primary.bin

### ISSUE THREAD

**Issue by gromez** [MenosGrante/Rekado#66]
Hello,

Is it possible to include the latest version of fusee-primary: https://github.com/Atmosphere-NX/Atmosphere/releases/download/0.10.0/fusee-primary.bin
For those who want to boot faster and don't need hekate.

Thanks!

**Comment by MenosGrante** [comment]
Hey, the latest Fusee Primary was bundled in [3.3.1](https://github.com/MenosGrante/Rekado/releases/tag/3.3.1) update, released recently.

**Comment by gromez** [comment]
@MenosGrante great, thanks!

**Comment by nbalonso** [comment]
Any chance the version number can be displayed?

**Comment by MenosGrante** [comment]
Yeah, that feature will be added in the future :)
