### ISSUE TITLE
Add Bluetooth option to send data

### ISSUE THREAD

**Issue by ilie321** [MenosGrante/Rekado#69]
As title says
Maybe we can find a dongle Bluetooth to serial +serial to usb-c and use it when needed

**Comment by ilie321** [comment]
https://www.aliexpress.com/item/33052237256.html + https://aliexpress.com/item/32910602341.html + https://aliexpress.com/item/4000268483869.html =2.5$  maybe

**Comment by MenosGrante** [comment]
I guess it will overcomplicate the application and a little part of users will try to use it.
