### ISSUE TITLE
Update application from itself

### ISSUE THREAD

**Issue by Ninjistix** [MenosGrante/Rekado#71]
Is it possible to add an auto updater into the app? or a notification for a new version release.

**Comment by MenosGrante** [comment]
I am working on new scheme for payloads, which will allow users to update payloads from the application. No ETA.

**Comment by Ninjistix** [comment]
well this is more of an auto update for the application itself, and not as much as the payloads.

**Comment by MenosGrante** [comment]
Added in the 4.1 update.
