### ISSUE TITLE
Adding payload from file not working

### ISSUE THREAD

**Issue by PhoenixFlaccus** [MenosGrante/Rekado#75]
Updated from 3.3(sic) to 4 today and when I tried adding hekate 5.1.4 from file it just didn't do anything: no error, not added to the list.  Downgraded to 3.4(sic) and it worked again.

**Comment by MenosGrante** [comment]
Okay, let me take a look.

**Comment by MenosGrante** [comment]
Fixed, fix will be present in 4.1 update in a few days.
