### ISSUE TITLE
Re-add multilanguage?

### ISSUE THREAD

**Issue by unbranched** [MenosGrante/Rekado#76]
I see you now use Onesky only, but why removing all translations from v4.0 ? Even those at 100%...

**Comment by MenosGrante** [comment]
I just haven't updated it for 4.0 yet, will do it after 4.0 stabilization.

**Comment by MenosGrante** [comment]
New strings for 4.1 update are finally finished and available at the OneSky - http://rekundevelopment.oneskyapp.com/collaboration/project?id=336657
