### ISSUE TITLE
[Request] Restore Reinx as a pre-installed payload

### ISSUE THREAD

**Issue by BlancBestGirl** [MenosGrante/Rekado#78]
Recently, Reinx 3.0 was released, which provides support for 9.x and 10.x. As it is now a viable choice once more as a cfw, it should be restored as a default payload, as before it was arguably a dead project and was not recommended by most to use.

**Comment by dbw-holic** [comment]
Yes, can you please add this payload back as one of the default options?

**Comment by MenosGrante** [comment]
Yes, after project resurrection, I will definitely add it back in 4.1 update.

**Comment by dbw-holic** [comment]
> Yes, after project resurrection, I will definitely add it back in 4.1 update.

Thank you so much mate!

**Comment by MenosGrante** [comment]
Added in the 4.1 update.
