### ISSUE TITLE
About Rekado Screen Slightly Cutoff

### ISSUE THREAD

**Issue by OrGoN3** [MenosGrante/Rekado#84]
Not a bug, but I figured you would want it displayed correctly. I'm using a Google Pixel 3 with Android 10 (all vanilla, nothing custom). The new app looks great, except the Twitter info gets cut off. Here's a picture! Oh and I cannot scroll down to see the rest of the screen. The app won't let me.

Edit: to clarify, I can scroll down on that page. However I can't scroll down any further than the picture below.
![Screenshot_20200802-025402](https://user-images.githubusercontent.com/56672656/89117437-caf71100-d46b-11ea-9e88-d7c1c0bdce1d.png)

**Comment by MenosGrante** [comment]
Yeah, seems like I forgot about the scrolling :D Will fix it for the next build. Thank you!

**Comment by MenosGrante** [comment]
Fixed as part of 4.1 Build 73 update.
