### ISSUE TITLE
Can't update bundled payloads

### ISSUE THREAD

**Issue by Crissal1995** [MenosGrante/Rekado#86]
Like title said, on the latest version of Rekado (4.1 at the moment of writing), I am unable to update payload(s?), in particular **fusee_primary** to the latest version 0.14.2.

I already tried to do a "refresh" of the page, swiping from top to bottom, but no update was found. 
If it's worth something, I manually added another payload, LockpickRCM, but I can't see how this can break the update feature.

By the way, I'll leave a screenshot of the payload section of the app. 
My phone is a OnePlus 7t EUR. 

![Screenshot_20200913-062241](https://user-images.githubusercontent.com/9823755/93010166-af624880-f589-11ea-94ee-3c836f235816.jpg)

**Comment by MenosGrante** [comment]
I just haven't uploaded the update for the fusee_primary, because it was not updated since 0.14.0.

**Comment by Crissal1995** [comment]
It's not better to just look for the latest release from other repos, instead of uploading manually?

**Comment by MenosGrante** [comment]
Yeah, but the code for such functionality will be bigger than the whole app itself 👍
