### ISSUE TITLE
Is there source code for magta and penza lib?   

### ISSUE THREAD

**Issue by ELY3M** [MenosGrante/Rekado#91]
It would be good idea to include source code for the libs used in the app.

**Comment by MenosGrante** [comment]
That is libs from my other apps and I don't want to include source code of it in open-source apps.

**Comment by ELY3M** [comment]
it is bad idea to put closed source libs in open sourced apps.
I was so mad.

**Comment by ELY3M** [comment]
I really hate this trash app.

**Comment by MenosGrante** [comment]
I am really happy, that you have your own version of the same app :)
