### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by f0li083** [MenosGrante/Rekado#94]
Hi, 

Thanks for the new release. I have a problem with 4.1.2 After installation it force closes when starting the app. I have uninstalled the previous version and cleared caches etc but still the problem remains. Android 11 OnePlus 8 Pro

**Comment by f0li083** [comment]
[logcat_04-17-2021_22-31-55.txt](https://github.com/MenosGrante/Rekado/files/6330079/logcat_04-17-2021_22-31-55.txt)

**Comment by CuBiC3D** [comment]
Can't provide more info right now, but OnePlus 6 on Android 10 same thing after updating to 4.1.2

**Comment by dothackjhe** [comment]
I second the issue. It also would not run on my Nokia 6.1.

**Comment by pixeltester** [comment]
Same problem here if it needs any further confirmation, immediate close/crash.

**Comment by LiloBzH** [comment]
Same on S9

**Comment by xorwin** [comment]
Pixel 4, android 11, the same issue

**Comment by yarizaderboss** [comment]
Galaxy S8, Android 9 Samen issue

**Comment by eifelkenny** [comment]
Here on Xiaomi Mi 9T FC as well. Hope @MenosGrante is already fixing this issue.

**Comment by qazrfv1234** [comment]
HTC U12+,Android 8,the same issue

**Comment by MenosGrante** [comment]
Hi everyone, I am checking this issue and will release new build, when the fix will be ready.

**Comment by f0li083** [comment]
Thank you!

**Comment by BaamAlex** [comment]
Same issue here. Mi Mix 2S with crDroid 6.15 (Android 10). 4.1.1 works fine and 4.1.2 force closes.

**Comment by MenosGrante** [comment]
Hi guys, could someone help me with testing the new build? Connect with me on [Telegram](https://t.me/menosgrante), please.

**Comment by MenosGrante** [comment]
The issue should be resolved with the 4.1.3 release.2

**Comment by Mostafa4410Mostafa44104** [comment]
30
