### ISSUE TITLE
[Suggestion] Current bundled payloads

### ISSUE THREAD

**Issue by pixeltester** [MenosGrante/Rekado#95]
Just some feedback: there's really no point in bundling fusee-primary and hekate as they are updated often and this app is not. Ideally you should redirect users to add their own payloads rather than potentially use outdated payloads.

ReiNX is also completely dead, discontinued almost a year ago.

**Comment by MenosGrante** [comment]
@pixeltester there are bundled payloads-updater in the app, which will let you know if any of the bundled payloads updates. However, unbundling any of the payloads may make my life a little bit easier 👍 I will think about this, thank you.
