### ISSUE TITLE
[Enhancement] Please keep fuseeprimary updated (0.19.2)

### ISSUE THREAD

**Issue by OrGoN3** [MenosGrante/Rekado#98]
Fusee-primary was quickly updated through 0.19.1, but then stopped. Why not have the app check https://github.com/Atmosphere-NX/Atmosphere/releases/latest/download/fusee-primary.bin and if different it asks to download new payload? You can then get the version from another request to the latest version.

**Comment by ELY3M** [comment]
yea I did in my app  :)

**Comment by OrGoN3** [comment]
> yea I did in my app :)

That's great, but the enhancement request I made is for Rekado. I find advertising another, similar piece of software on someone else's GitHub bug tracker to be in very bad taste.

**Comment by MenosGrante** [comment]
I am keeping updating payloads without updating APK itself, it should notify you, when new payloads are available. If not, try to pull down the screen on the "Payloads" screen and it will do manual check for updates.

**Comment by ELY3M** [comment]
This app is useless!  Try nxloader103

**Comment by OrGoN3** [comment]
> I am keeping updating payloads without updating APK itself, it should notify you, when new payloads are available. If not, try to pull down the screen on the "Payloads" screen and it will do manual check for updates.

This was mainly a request to automate the updates, even though I didn't explicitly mention it. At the time of the request, fusee-primary updated (the very few times it changes) and there was a good delay in it being updated here. I understand you have a life and other things, which if why I thought about automating the updates.
Thanks for this awesome app!
