### ISSUE TITLE
[Enhancement] Add an in-app updater

### ISSUE THREAD

**Issue by MasterLuma** [MenosGrante/Rekado#99]
Perhaps add an in-app update option whenever Rekado gets an update so one won't have to download another apk.

**Comment by MenosGrante** [comment]
There is a built-in in-app updater in the Rekado, but since new builds are not coming that frequent you may haven't seen it.

**Comment by MenosGrante** [comment]
I am also working on removing all closed-source code from Rekado to make it available in the F-Droid.
